#!/bin/sh

brightness_path="/sys/class/leds/tpacpi::kbd_backlight/brightness"

if [ $(cat $brightness_path) -eq 0 ]; then
  echo 100 | sudo tee $brightness_path
else
  echo 0 | sudo tee $brightness_path
fi
