#!/bin/sh

set -eu

function get_audio {
  muted=$(pacmd list-sinks | grep muted | awk '{print $2}') 
  if [ $muted == "yes" ]; then
    echo "A: -"
  else
    echo "A: $(amixer sget Master | grep % | tail -n 1 | awk -F '[][]' '{print $2}')"
  fi
}

function get_microphone {
  muted=$(amixer | grep Capture | tail -n 1 | awk -F '[][]' '{print $4}')
  if [ $muted == "off" ]; then
    echo "M: -"
  else
    echo "M: $(amixer | grep Capture | tail -n 1 | awk -F '[][]' '{print $2}')"
  fi
}

function get_brightness {
  echo "B: $(xbacklight -get | awk '{print int($1/10)*10}')%"
}

function get_internet {
  ethernet_connected=1
  ethernet_string="No Ethernet"
  if $(ifconfig enp0s25 | grep -q inet); then
    ethernet_string="Ethernet"
    ethernet_connected=0
  fi

  wireless_connected=1
  wireless_string="No WiFi"
  if iwgetid > /dev/null; then
	  wireless_string="$(iwgetid -r) ($(iwconfig wlp3s0 | grep Signal | awk '{print $2}' | awk -F '=' '{print $2}'))"
    wireless_connected=0
  fi

  output="I: "
  if [ $ethernet_connected -eq 0 ]; then
    output="$output$ethernet_string"
  fi
  if [ $ethernet_connected -eq 0 ] && [ $wireless_connected -eq 0 ]; then
    output="$output, "
  fi
  if [ $wireless_connected -eq 0 ]; then
    output="$output$wireless_string"
  fi
  if [ $ethernet_connected -eq 1 ] && [ $wireless_connected -eq 1 ]; then
    output="I: No Internet"
  fi

  echo $output
}

function vpn {
  if $(systemctl status openvpn-$1 | grep -q running); then
    echo "☻"
  else
    echo "-"
  fi
}

function get_kubeconfig {
	context=$(kubectl config current-context | sed 's/giantswarm-//g')
	namespace=$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\""$(kubectl config current-context)"\")].context.namespace}")
	echo "K: $context/$namespace"
}

function battery_info {
  echo $(acpi | grep "Battery $1" | awk '{print $3 $4}' | awk -F ',' '{print $1 " " $2}' | \
	  sed -e 's/Charging/⚡/g' | \
	  sed -e 's/Discharging/○/g' | \
	  sed -e 's/Unknown/-/g' | \
	  sed -e 's/Full/☻/g'
	)
}

function date_info {
  echo "$(date '+%H:%M %d/%m/%y')"
}

function bar {
  echo "$(get_audio) | \
$(get_microphone) | \
$(get_brightness) | \
$(get_internet) | \
$(get_kubeconfig) | \
VPN: $(vpn gridscale) $(vpn vultr) | \
$(battery_info 0), $(battery_info 1) | \
$(date_info)"
}

while true; do
  bar
  sleep 1
done
