#!/bin/sh

path="$(tmux display-message -p -F "#{pane_current_path}")"
git_branch=$(cd ${path}; git rev-parse --abbrev-ref HEAD 2> /dev/null)

path_info="${path}"
git_info=""
if [ ! -z "$git_branch" ]; then
  git_info=" (${git_branch})"
fi

echo ${path_info}${git_info}
